# Ansible playbook
- hosts: all
  remote_user: rex
  sudo: yes
  tasks:
    - name: adding apt repository
      apt_repository:
        repo: 'ppa:longsleep/golang-backports'
    - name: apt install
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - git
        - curl
        - golang-go
        - apache2
        - apache2-utils
        - libapache2-mod-security2
        - chromium-browser
    - name: Cloning ModSecurity Core Rule Set
      git:
        repo: https://github.com/SpiderLabs/owasp-modsecurity-crs.git
        dest: /etc/modsecurity/crs
    - name: Copying apache2.conf
      copy:
        src: ./deploy/apache2.conf
        dest: /etc/apache2/apache2.conf
    - name: Copying modsecurity.conf
      copy:
        src: ./deploy/modsecurity.conf
        dest: /etc/modsecurity/modsecurity.conf
    - name: Copying crs-setup.conf
      copy:
        src: ./deploy/crs-setup.conf
        dest: /etc/modsecurity/crs/crs-setup.conf
    - name: Copying unitfile
      copy:
        src: ./deploy/gyotaku.service
        dest: /etc/systemd/system/gyotaku.service
      notify: gyotaku-reload
    - name: Enabling Apache modules
      command: a2enmod security2 proxy proxy_http
      notify: restart apache2
    - name: Disabling 000-default
      command: a2dissite 000-default
      notify: restart apache2
    - name: Deploying gyotaku
      git: 
        repo: git@github.com:rekkusu/gyotaku.git
        dest: /opt/go/src/github.com/rekkusu/gyotaku
        accept_hostkey: yes
        key_file: /home/rex/.ssh/id_rsa
      notify: gyotaku
    - name: go get ./...
      shell: GOPATH=/opt/go go get ./...
      args:
        chdir: /opt/go/src/github.com/rekkusu/gyotaku
      notify: gyotaku

  handlers:
    - name: restart apache2
      systemd:
        name: apache2
        state: restarted
    - name: gyotaku-reload
      systemd:
        name: gyotaku
        daemon_reload: yes
    - name: gyotaku
      systemd:
        name: gyotaku
        state: restarted
        enabled: yes

